language: android
android:
  components:
    - build-tools-20.0.0
    - android-20
sudo: false
jdk:
- openjdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_d7cddead3109_key -iv $encrypted_d7cddead3109_iv -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6508d3ba06fa0d2b5ffc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
